apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "beam-simulation.name" . }}
  labels:
    app: {{ .Values.service.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.deployment.config.cluster_size }}
  selector:
    matchLabels:
      app: {{ template "beam-simulation.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "beam-simulation.name" . }}
        actorSystemName: {{ .Values.configmap.actorSystemName }}
    spec:
      containers:
      - name: {{ template "beam-simulation.name" . }}
        image: "{{ .Values.deployment.image }}:{{ .Values.deployment.imageVersion }}"
        imagePullPolicy: {{ .Values.deployment.pullPolicy }}
        envFrom:
          - configMapRef:
              name: {{ template "beam-simulation.name" . }}
        env:
        - name: HOST_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: POD_BIND_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: AKKA_REMOTING_BIND_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        ports:
        # akka remoting
        - name: remoting
          containerPort: 2552
          protocol: TCP
        # akka-management bootstrap
        - name: bootstrap
          containerPort: 8558
          protocol: TCP
        # external http
        - name: akka-mgmt-http
          containerPort: 8558
          protocol: TCP
      imagePullSecrets:
        - name: {{ .Values.deployment.pullSecret }}