apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: {{ template "beam-simulation.data" . }}
    {{- include "beam-simulation.release_labels" . | indent 4 }}
  name: {{ template "beam-simulation.data" . }}
  namespace: {{ template "beam-simulation.namespace" . }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "4"
spec:
  selector:
    matchLabels:
      app: {{ template "beam-simulation.data" . }}
  template:
    metadata:
      labels:
        app: {{ template "beam-simulation.data" . }}
    spec:
      containers:
        - name: s3-{{ template "beam-simulation.data" . }}
          image: {{ .Values.daemonset.image }}:{{ .Values.daemonset.imageTag }}
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          # use ALL  entries in the config map as environment variables
          env:
            - name: S3_BUCKET
              value: {{ .Values.daemonset.bucket }}
            - name: S3_REGION
              value: {{ .Values.daemonset.region }}
            - name: AWS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "beam-simulation.secret" . }}
                  key: aws-key
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "beam-simulation.secret" . }}
                  key: aws-secret-key
          volumeMounts:
            - name: {{ .Values.volume.fuse.name }}
              mountPath: {{ .Values.volume.fuse.path }}
            - name: {{ .Values.volume.data.name }}
              mountPath: {{ .Values.volume.data.path }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", {{ printf "sleep 5 && cp -rv /data/beamville /data/dtd /data/common %s/"  .Values.volume.data.path | quote }}]
      imagePullSecrets:
        - name: {{ .Values.secret.docker }}
      volumes:
        - name: {{ .Values.volume.fuse.name }}
          hostPath:
            path: {{ .Values.volume.fuse.host }}
        - name: {{ .Values.volume.data.name }}
          hostPath:
            path: {{ .Values.volume.data.host }}