apiVersion: v1
kind: Namespace
metadata:
  name: {{ template "beam-simulation.namespace" . }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "1"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ template "beam-simulation.resources" . }}
  namespace: {{ template "beam-simulation.namespace" . }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "2"
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 3Gi