language: scala
scala:
  2.12.1
jdk:
  - oraclejdk8
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - zip -r beam.zip beam/build/libs beam/test beam/appspec.yml || true
  - mkdir -p "dpl_cd_upload"
  - mv beam.zip dpl_cd_upload/beam.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    bucket: beam-builds
    region: us-east-2b
    skip_cleanup: true
    on:
      repo: LBNL-UCB-STI/beam
      all_branches: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: beam-builds
    key: beam.zip
    bundle_type: zip
    application: Beam
    deployment_group: BeamDeploymentGroup
    region: us-east-2b
    on:
      repo: LBNL-UCB-STI/beam
      all_branches: true

after_deploy:
  - echo "Performing after deploy procedures..."

notifications:
  webhooks:
    urls:
      - https://hooks.glip.com/webhook/d238705c-0001-4d98-81c1-3402db81911b
    on_success: change 
    on_failure: always 
    on_start: never 
