apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "1"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ template "beam-simulation.resources" . }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "2"
spec:
  hard:
    requests.cpu: "28"
    requests.memory: 58Gi
    limits.cpu: "30"
    limits.memory: 62Gi