version: '3'
services:

  beam-simulation:
    image: beammodel/beam
    hostname: beam_worker
    ports:
      - "2552"
    volumes:
      - "../test/input/sf-light:/opt/config/simulation"
      - "../test/input/common:/opt/config/common"
      - "../output/docker:/opt/output:rw"
    command: ["--config",  "/opt/config/simulation/sf-light.conf"]
    environment:
      BEAM_OUTPUT: "/opt/output"
    deploy:
      replicas: 1