version: '3'
services:

  beam-worker:
    image: beammodel/beam
    env_file:
      - beam-variables.env
    ports:
      - "2552"
    volumes:
      - "../test/input/beamville:/opt/config/simulation"
      - "../test/input/common:/opt/config/common"
      - "../test/input/dtd:/opt/config/dtd"
      - "../output/docker:/opt/output:rw"
    command: --config="/opt/config/simulation/beam.conf" --cluster-type=worker --node-host=$$HOSTNAME_VALUE --node-port=2552 --seed-address="beam-master:2552"
    environment:
      HOSTNAME_COMMAND: "ifconfig | grep \"inet addr:\" | awk  -F'[: ]+' '!/127/{print $$4}'"
      BEAM_OUTPUT: /opt/output

  beam-master:
    image: beammodel/beam
    hostname: beam-master
    ports:
      - "2552"
    volumes:
      - "../test/input/beamville:/opt/config/simulation"
      - "../test/input/common:/opt/config/common"
      - "../test/input/dtd:/opt/config/dtd"
      - "../output/docker:/opt/output:rw"
    command: ["--config",  "/opt/config/simulation/beam.conf", "--cluster-type", "master", "--node-host", "beam-master", "--node-port", "2552", "--seed-address", "beam-master:2552"]
    environment:
      BEAM_OUTPUT: /opt/output
    depends_on:
      - beam-worker