service:
  name: beam-service
  akkaPort:
    name: "akka-remote"
    type: None
    port: 2552

deployment:
  image: ${beamImage}
  imageTag: ${beamImageTag}
  pullPolicy: Always
  pullSecret: dockerhub
  # Additional pod labels
  # ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  podLabels: {}

volume:
  data:
    name: mount-data
    path: /s3data
    host: /dev/data-s3fs
  output:
    name: storage
    path: /dev/data-out

job:
  hostname: beam-master
  image: ${beamImage}
  imageTag: ${beamImageTag}
  resources:
    limits:
      cpu: 300m
      memory: 2G
    requests:
      cpu: 300m
      memory: 1G

global:
  namespace: ${simulationNamespace}
  creation: ${creationTime}
  secret:
    docker: dockerhub
