service:
  name: beam-service
  akkaPort:
    name: "akka-remote"
    type: None
    port: 2552

deployment:
  image: ${beamImage}
  imageTag: ${beamImageTag}
  pullPolicy: Always
  pullSecret: dockerhub
  # Additional pod labels
  # ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  podLabels: {}

volume:
  data:
    name: mount-data
    path: /s3data
    host: /dev/data-s3fs
  output:
    name: storage
    path: /data-output
    host: /dev/data-out

job:
  hostname: beam-master
  image: ${beamImage}
  imageTag: ${beamImageTag}
  config: ${simulationConfig}
  jvm: '"-Xmx28G" "-Xms14G"'
  resources:
      cpu: ${cpu}
      memory: ${mem}

global:
  namespace: ${simulationNamespace}
  creation: ${creationTime}
  secret:
    docker: dockerhub
