service:
  name: beam-service
  akkaPort:
    master:
      name: "akka-remote"
      type: None
      port : "2552"
    worker:
      name: "akka-remote"
      type: None
      port: 2552

deployment:
  image: ${beamImage}
  imageTag: ${beamImageTag}
  pullPolicy: Always
  pullSecret: dockerhub
  # Additional pod labels
  # ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  podLabels: {}

volume:
  data:
    name: mount-data
    path: /s3data
    host: /dev/data-s3fs
  output:
    name: storage
    path: /opt/output

job:
  master:
    hostname: beam-master
  worker:
    hostname: beam-worker
    replicas: 3
  image: ${beamImage}
  imageTag: ${beamImageTag}

global:
  namespace: ${simulationNamespace}
  creation: ${creationTime}
  secret:
    docker: dockerhub
