service:
  name: beam-service
  akkaPort:
    name: "akka-remote"
    type: None
    port: 2552

secret:
  docker: dockerhub

deployment:
  image: "beammodel/beam"
  imageTag: "latest"
  pullPolicy: Always
  pullSecret: dockerhub
  # Additional pod labels
  # ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  podLabels: {}

daemonset:
  image: "kmitin/s3fs"
  imageTag: "latest"
  bucket: "beam-config"
  region: "us-west-2"
  pullPolicy: Always

volume:
  fuse:
    name: devfuse
    path: /dev/fuse
    host: /dev/fuse
  data:
    name: mount-data
    path: /s3data
    host: /dev/data-s3fs
  output:
    name: storage
    path: /opt/output

job:
  hostname: beam-master
  image: "beammodel/beam"
  imageTag: "latest"
