apiVersion: v1
kind: Secret
metadata:
  name: s3fs-secret
  namespace: default
type: Opaque
data:
  aws-key: QUtJQVU2SzRHUFBOTklXS0MzRUs=
  aws-secret-key: R3FZd2dEL0s4a21rcXJUMlpsQ1JWNFYzK2p1SW02bkl2TmtIbmJMNg==