apiVersion: v1
kind: Pod
metadata:
  name: beam-master
  labels:
    app: beam-master
    app.kubernetes.io/name: beam-simulation
    app.kubernetes.io/instance: beam-master
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: master
    app.kubernetes.io/managed-by: helm
spec:
  hostname: beam-master
  restartPolicy: Never

  volumes:
    - name: output-storage
      emptyDir: {}
    - name: data-storage
      emptyDir: {}
    - name: mount-storage
      emptyDir: {}
    - name: devfuse
      hostPath:
        path: /dev/fuse

  imagePullSecrets:
    - name: dockerhub

  containers:

    - name: beam-simulation-s3fs
      image: kmitin/s3fs:latest
      imagePullPolicy: Always
      securityContext:
        privileged: true
      resources:
        limits:
          cpu: 300m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
      env:
        - name: S3_BUCKET
          value: beam-config
        - name: S3_REGION
          value: us-west-2
        - name: AWS_KEY
          valueFrom:
            secretKeyRef:
              name: s3fs-secret
              key: aws-key
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: s3fs-secret
              key: aws-secret-key
      lifecycle:
        postStart:
          exec:
            command: ["/bin/bash", "-c", "sleep 10 && cp -rv /data/beamville /data/dtd /data/common /s3data/"]
      volumeMounts:
        - name: data-storage
          mountPath: /s3data
        - name: mount-storage
          mountPath: /data
        - name: devfuse
          mountPath: /dev/fuse

    - name: beam-simulation
      image: beammodel/beam
      resources:
        limits:
          memory: "4G"
        requests:
          memory: "3G"
      args: ["--config",  "/opt/config/beamville/beam.conf", "--cluster-type", "master", "--node-host", "beam-master", "--node-port", "2552", "--seed-address", "beam-master:2552", "--use-local-worker", "true"]
      imagePullPolicy: Always
      env:
        - name: BEAM_OUTPUT
          value: /opt/output
        - name: JAVA_OPTS
          value: '"-Xmx3G" "-Xms2G" "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"'
      # livenessProbe:
      #   exec:
      #     command: ["/bin/bash", "-c", "netstat -tulnp | grep 2552"]
      #   initialDelaySeconds: 5
      #   periodSeconds: 5
      ports:
        # akka remoting
        - name: remoting
          containerPort: 2552
          protocol: TCP
      volumeMounts:
        - name: output-storage
          mountPath: /opt/output
        - name: data-storage
          mountPath: /opt/config
