apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: data-provider
  name: data-provider
spec:
  selector:
    matchLabels:
      app: data-provider
  template:
    metadata:
      labels:
        app: data-provider
    spec:
      containers:
        - name: s3fuse
          image: kmitin/s3fs:latest
          securityContext:
            privileged: true
          # use ALL  entries in the config map as environment variables
          env:
            - name: S3_BUCKET
              value: beam-config
            - name: S3_REGION
              value: us-west-2
            - name: AWS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3fs-secret
                  key: aws-key
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3fs-secret
                  key: aws-secret-key
          volumeMounts:
            - name: devfuse
              mountPath: /dev/fuse
            - name: mount-data
              mountPath: /s3data
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "sleep 10 && cp -rv /data/beamville /data/dtd /data/common /s3data/"]
      imagePullSecrets:
        - name: dockerhub
      volumes:
        - name: devfuse
          hostPath:
            path: /dev/fuse
        - name: mount-data
          hostPath:
            path: /dev/data-s3fs