
service:
  name: beam-service
  akkaPort:
    name: "akka-port"
    type: None
    externalPort: 2551
    targetPort: 2551
  bootstrapPort:
    name: "bootstrap-port"
    externalPort: 8558
    targetPort: 8558

deployment:
  image: "beammodel/beam"
  imageVersion: "latest"
  pullPolicy: Always
  pullSecret: dockerhub
  container:
      name: "akka-remote"
      akkaPort: 2551
  config:
    cluster_size: 1
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: OnDelete
  # Additional pod labels
  # ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  podLabels: {}

configmap:
  actorSystemName: "BeamSimulation"
  clusterJoinTimeOut: 5000
  kubecontext: "beam-dev-context"




