apiVersion: v1
kind: Pod
metadata:
  name: beam-worker
  labels:
    app: beam-worker
    app.kubernetes.io/name: beam-simulation
    app.kubernetes.io/instance: beam-worker
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: worker
    app.kubernetes.io/managed-by: helm
spec:
  hostname: beam-worker
  restartPolicy: Never
  dnsPolicy: ClusterFirst

  volumes:
  - name: output-storage
    emptyDir: {}
  - name: data-storage
    hostPath:
      path: /dev/data-s3fs
  
  imagePullSecrets:
    - name: dockerhub

  containers:

  - name: beam-simulation
    image: beammodel/beam:latest
    resources:
      limits:
        memory: "2G"
      requests:
        memory: "1G"
    args: ["--config",  "/opt/config/beamville/beam.conf", "--cluster-type", "worker", "--node-host", "beam-worker", "--node-port", "2552", "--seed-address", "beam-master:2551"]
    imagePullPolicy: Always
    env:
      - name: BEAM_OUTPUT
        value: /opt/output
      - name: JAVA_OPTS
        value: '"-Xmx2G" "-Xms1G" "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"'
    ports:
      # akka remoting
      - name: remoting
        containerPort: 2552
        protocol: TCP
      - name: debug
        containerPort: 5005
        hostPort: 5005
        protocol: TCP
    volumeMounts:
      - name: output-storage
        mountPath: /opt/output
      - name: data-storage
        mountPath: /opt/config
