apiVersion: v1
kind: Service
metadata:
  labels:
    app: beam-local-simulation
  name: beam-local-simulation
spec:
  clusterIP: None
  ports:
  - port: 2552
  selector:
    app: beam-master-local
    