apiVersion: v1
kind: Service
metadata:
  labels:
    app: beam-master
  name: beam-master
spec:
  clusterIP: None
  ports:
  - port: 2551
    name: remoting
  - port: 5006
    name: debug
  selector:
    app: beam-master
---
apiVersion: v1
kind: Pod
metadata:
  name: beam-master
  labels:
    app: beam-master
    app.kubernetes.io/name: beam-simulation
    app.kubernetes.io/instance: beam-master
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: master
    app.kubernetes.io/managed-by: helm
spec:
  hostname: beam-master
  restartPolicy: Never
  dnsPolicy: ClusterFirst

  volumes:
  - name: output-storage
    emptyDir: {}
  - name: data-storage
    hostPath:
      path: /dev/data-s3fs
  
  imagePullSecrets:
    - name: dockerhub

  containers:

  - name: beam-simulation
    image: beammodel/beam:latest
    resources:
      limits:
        memory: "2G"
      requests:
        memory: "1G"
    args: ["--config",  "/opt/config/beamville/beam.conf", "--cluster-type", "master", "--node-host", "beam-master", "--node-port", "2551", "--seed-address", "beam-master:2551"]
    imagePullPolicy: Always
    env:
      - name: BEAM_OUTPUT
        value: /opt/output
      - name: JAVA_OPTS
        value: '"-Xmx2G" "-Xms1G" "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5006"'
    ports:
      # akka remoting
      - name: remoting
        containerPort: 2551
        protocol: TCP
      - name: debug
        containerPort: 5006
        protocol: TCP
    volumeMounts:
      - name: output-storage
        mountPath: /opt/output
      - name: data-storage
        mountPath: /opt/config
