apiVersion: v1
kind: Secret
metadata:
  name: dockerhub
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJrbWl0aW4iLCJwYXNzd29yZCI6IkVzaTQxMTAyMCIsImVtYWlsIjoibWl0aW4ua2lyaWxsLm9sQGdtYWlsLmNvbSIsImF1dGgiOiJhMjFwZEdsdU9rVnphVFF4TVRBeU1BPT0ifX19
---
apiVersion: v1
kind: Secret
metadata:
  name: s3fs-secret
type: Opaque
data:
  # base64 encoded keys
  # echo -n "AWS_KEY|AWS_SECRET_KEY" | base64
  aws-key: QUtJQVU2SzRHUFBOTklXS0MzRUs=
  aws-secret-key: R3FZd2dEL0s4a21rcXJUMlpsQ1JWNFYzK2p1SW02bkl2TmtIbmJMNg==